### ISSUE TITLE
Thank you so much.

### ISSUE THREAD

**Issue by 1c7** [sterpe/yt-timedtext2srt#2]
## Some background info.
I am the author of this program: https://greasyfork.org/en/scripts/5367-youtube-auto-subtitle-downloader-v6
This little script help people download youtube auto subtitle.
Just yesterday, User feedback says it's not working anymore,
And after little debug, I saw youtube change auto subtitle xml format .

## And
 your program is very helpful to me to write new logic to parse this new format. Thanks.
(I am still fixing the problem. I haven't finish it yet. but thanks in advance 😄 )
(you can close this issue after reading it)

**Comment by sterpe** [comment]
+1, glad it helps.

**Comment by sterpe** [comment]
Also @1c7 if you use the `&fmt=srv1` parameter when you call timedtext api endpoint `https://www.youtube.com/api/timedtext?` you will be able to request  specific version of timedtext format, ie: `srv1`, `srv2`, `srv3`.  Looks like your code is expecting `srv1`.

**Comment by 1c7** [comment]
@sterpe  Thank you
you save me another 1 hour of time.
LOL

**Comment by 1c7** [comment]
I fixed the problem. 
now the newest version is v7, 
Thank you very much!
