### ISSUE TITLE
Empty lines and NaN:NaN:NaN,NaN timestamps

### ISSUE THREAD

**Issue by vers-one** [sterpe/yt-timedtext2srt#3]
Steps to reproduce:

1. Download srv3 file for this video: https://www.youtube.com/watch?v=2A5myDShVbo
2. Run `cat timedtext | yt-timedtext2srt > subtitles.srt`

This produces an srt file with every second line being empty:

```
0
00:00:00,570 --> 00:00:05,9
<normal text>

1
00:00:02,869 --> 00:00:05,9


2
00:00:02,879 --> 00:00:08,610
<normal text>

3
00:00:04,999 --> 00:00:08,610


4
00:00:05,9 --> 00:00:12,269
<normal text>

5
00:00:08,600 --> 00:00:12,269

```

It also produces six lines with `NaN:NaN:NaN,NaN` timestamp which breaks every player I've tried it with.

This is the first occurrence:
```
671
00:12:14,590 --> NaN:NaN:NaN,NaN
```

**Comment by sterpe** [comment]
@vers-one That file is not youtube's timed text version3

**Comment by sterpe** [comment]
@vers-one That file is not youtube's timed text version3, looks like some new JSON format, however version 3 is the only format this library supports.

**Comment by sterpe** [comment]
@vers-one That file is not youtube's timed text version3 which is an xml format, the video link you shared looks like it receives some new JSON format, however version 3 is the only format this library supports.
